---
- name: Install "yo" package globally.
  npm: name=yo global=yes

- name: Install "jspm" package globally.
  npm: name=jspm@beta global=yes

- name: Registry jspm for npm.
  command: "jspm config registries.github.auth {{ lookup('env', 'JSPM_GITHUB_AUTH_TOKEN') }}"
  args:
    chdir: /home/vagrant/app/client
  sudo: no

- name: Install "jspm" packages.
  command: "jspm install -y"
  args:
    chdir: /home/vagrant/app/client
  sudo: no

- name: Install "yeoman-node" node.js package globally.
  npm: name=generator-node global=yes

- name: Install "yeoman-aurelia" package globally.
  npm: name=generator-aurelia global=yes

- name: Install "mocha" node.js package globally.
  npm: name=mocha global=yes
