---
- name: Install "yo" package globally.
  npm: name=yo global=yes

- name: Isntall "jspm" pckage globally.
  npm: name=jspm@beta global=yes

- name: Registry jspm for npm.
  command: "{{item}}"
  with_items:
    - jspm config registries.github.remote https://github.jspm.io
    - jspm config registries.github.auth {{ lookup('env', 'JSPM_GITHUB_AUTH_TOKEN') }}
    - jspm config registries.github.maxRepoSize 0
    - jspm config registries.github.handler jspm-github
  args:
    chdir: /home/vagrant/app/client
  sudo: no

- name: Install "jspm" packages.
  command: "jspm install -y"
  args:
    chdir: /home/vagrant/app/client
  sudo: no

- name: Install "yeoman-node" node.js package globally.
  npm: name=generator-node global=yes

- name: Install "yeoman-aurelia" package globally.
  npm: name=generator-aurelia global=yes

- name: Install "mocha" node.js package globally.
  npm: name=mocha global=yes
