---
- name: Install "yo" package globally.
  npm: name=yo global=yes

- name: Install "yeoman-node" node.js package globally.
  npm: name=generator-node global=yes

- name: Install "mocha" node.js package globally.
  npm: name=mocha global=yes

- name: Install "sinon" node.js package locally.
  npm: name=sinon path=/usr/vagrant/app

- name: Install "chai" node.js package locally.
  npm: name=chai path=/usr/vagrant/app
