---
- name: Install "yo" package globally.
  npm: name=yo global=yes

- name: Install "yeoman-node" node.js package globally.
  npm: name=generator-node global=yes

- name: Install "mocha" node.js package globally.
  npm: name=mocha global=yes
